// Configuration for Control Panel
// Automatically Generated by PhantomBot at Startup
// Do NOT Modify! Overwritten when PhantomBot is restarted!
var panelSettings = {
    panelPort   : 25004,
    channelName : "kd8lvt",
    auth        : "avV5jlL5m14TD7GbBiya9P41lWvDHV",
    http        : "http://"
,     displayName : "@DISPLAY_NAME@"
, };

function getPanelPort() { return panelSettings.panelPort; }
function getChannelName() { return panelSettings.channelName; }
function getAuth() { return panelSettings.auth; }
function getProtocol() { return panelSettings.http; }
function getDisplayName() { return panelSettings.displayName; }
